name: "Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - noetic
          - humble
          - iron
          - jazzy
          - rolling
        system:
          - x86_64-linux
          - aarch64-linux
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          max-jobs = 2
          cores = 2
          extra-platforms = aarch64-linux
    - uses: docker/setup-qemu-action@v2
    - uses: cachix/cachix-action@v12
      with:
        name: ros
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        skipPush: true
    - uses: ./.github/actions/nix-ros-build-action
      with:
        root-attribute: 'rosPackages.${{ matrix.distro }}'
        system: '${{ matrix.system }}'
        eval-jobs: 4
        build-jobs: 2
